apiVersion: v1
kind: Service
metadata:
  labels:
    author: vikash-soni
  name: db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-app
  