apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis-app
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
  template:
    metadata:
      labels:
        name: redis-app
    spec:
      containers:
      - image: redis:alpine
        name: redis-app
        ports:
        - containerPort: 6379
