apiVersion: v1
kind: Service
metadata:
  labels:
    author: vikash-soni
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-app
  