apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app
    author: vikash-soni
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      labels: 
        name: voting-app
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80