apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app
    author: vikash-soni
spec:
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      labels:
        name: worker-app
    spec:
      containers:
      - name: worker-app
        image: dockersamples/examplevotingapp_worker
      